//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportFacilitySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilityCheck
    {
        public int EntryID { get; set; }
        public int TransactionID { get; set; }
        public string FacilityID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int TimeSlot { get; set; }
        public string Activity { get; set; }
        public string NUSID { get; set; }
    }
}
