//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportFacilitySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityInformation
    {
        public string FacilityID { get; set; }
        public string Activity { get; set; }
        public string LocationTag { get; set; }
        public string Location { get; set; }
        public string Remarks { get; set; }
    }
}
